### ISSUE TITLE
Cayden - Mod Requests

### ISSUE THREAD

**Issue by CaydenCailean** [cocoacraft/cocoacraft#1]
- Tinkers' Construct, 
- Tinkers' Mechworks,
- ExtraUtilities,
- Obsidiplates,
- Bibliocraft,
- JABBA,
- IronChests,
- Redstone Arsenal,
- SecretRoomsMod.

**Comment by Karunamon** [comment]
Got it, thanks!

**Comment by CaydenCailean** [comment]
I forgot a few, sorry to be a bother.
- Ender Storage
- Thaumic Tinkerer
- BiblioWoods(Natura)
- Blood Magic.
