### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by Datraen** [cocoacraft/cocoacraft#9]
With the removal of Mystcraft and Dimensional Doors, I am asking again to have Twilight Forest added to the mod list.
http://www.minecraftforum.net/topic/561673-172-the-twilight-forest-v211-new-progression-system/
https://dl.dropboxusercontent.com/u/38679977/twilightforest-1.6.4-1.20.5.jar

**Comment by Karunamon** [comment]
Haven't fogotten you, but this is a dupe of #3 :)
